### ISSUE TITLE
Questions in dataset_reader.

### ISSUE THREAD

**Issue by pengshuang** [allenai/allennlp-bert-qa-wrapper#18]
Hi

https://github.com/allenai/allennlp-bert-qa-wrapper/blob/9a116416f14f04f4460992cdd5c3344b21f99bfd/pretrained_bert/dataset_reader.py#L143

https://github.com/allenai/allennlp-bert-qa-wrapper/blob/9a116416f14f04f4460992cdd5c3344b21f99bfd/pretrained_bert/dataset_reader.py#L194

Here (Line 143 - Line 194), if the input length exceeds the limit of **max_seq_length**, `return instance` would only return the first part of  input in **doc_spans**. Is this right?

**Comment by pdasigi** [comment]
@pengshuang  That is correct. I admit that the code there could have been written better (the for loop was unnecessary) and some comments there could have helped. If you want to fix it, and want to submit a PR, I would be grateful!

**Comment by pengshuang** [comment]
@pdasigi I think there is a "bug" here. We can not have documents that are longer than the maximum sequence length. Original pytorch-pretrained-bert does a sliding window approach but it doesn't take effect here because of this bug.
https://github.com/allenai/allennlp-bert-qa-wrapper/blob/9a116416f14f04f4460992cdd5c3344b21f99bfd/pretrained_bert/dataset_reader.py#L127
Here, not all doc_spans are converted into instances.

**Comment by pdasigi** [comment]
It is true that we are not making use of the sliding window here. The current behavior of returning just the first part of the paragraph is not optimal. That said, I'm not sure if the one in pytorch-pretrained-bert is optimal either. While breaking paragraphs into multiple chunks, it assumes that a given chunk is sufficient to answer a given question if it contains the answer span (while training). While this assumption might generally hold true for SQuAD, it feels strange to provide the model only a portion of the context that the human annotators had access to while writing questions. For example, the question could indeed require access to a longer context (say for resolving coreference). I think the right thing to do here is to ignore instances where the paragraphs are too long, and may be provide an option to do what was done in pytorch-pretrained-bert if we think we can make the assumption stated above for the dataset being processed.

**Comment by pengshuang** [comment]
@codeviking I understand. Thanks for your answer.
